# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty", "~> 0.7.0"

gem "tty-table", "~> 0.8.0"


gem "pastel", "~> 0.7.2"

gem "tty-font", "~> 0.5.0"

gem "tty-prompt", "~> 0.12.0"

gem "rspec", "~> 3.9"
